/**
 * Security headers, shared by both things this deploys as.
 *
 * The app injects markup it did not author into the DOM in three places — the
 * SVG figure, the Mermaid diagram, and the sanitiser's own forgiving-parser
 * fallback — and all three trace back to model output, which traces back to a
 * PDF someone else may have written. `src/lib/sanitizeSvg.ts` is an allowlist
 * and it fails closed, which is the right first line. This is the second one:
 * it decides what a gap in that allowlist would actually be worth.
 *
 * Everything the app loads is same-origin. The pdf.js worker ships in the
 * bundle, KaTeX's fonts and CSS are bundled, Mermaid is a dynamic import, and
 * the only host the client ever talks to is its own `/api`. So the policy is
 * `'self'` almost throughout, and the exceptions are worth naming:
 *
 *   style-src 'unsafe-inline'  React sets style props, KaTeX emits inline
 *                              styles, and Mermaid puts a <style> in its SVG.
 *                              Nothing here can be tightened without a nonce on
 *                              a static file, which is not available.
 *   img-src data: blob:        Vite inlines small assets as data URIs, and
 *                              Markdown permits data: images (never http).
 *   worker-src blob:           pdf.js falls back to a blob worker on engines
 *                              where the module worker will not start.
 *
 * The CSP is production-only. Vite's dev server injects its HMR client inline
 * and react-refresh needs `eval`, so `script-src 'self'` would break `npm run
 * dev` and nothing else. The headers that cost nothing in development are set
 * everywhere.
 */

const CSP_DIRECTIVES: readonly string[] = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "connect-src 'self'",
  "worker-src 'self' blob:",
  "manifest-src 'self'",
  "media-src 'none'",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
];

export const CONTENT_SECURITY_POLICY = CSP_DIRECTIVES.join('; ');

/**
 * Set on every response, in development too. None of these can break a dev
 * server, and a header that is only correct in production is a header nobody
 * notices is missing.
 */
export const BASE_SECURITY_HEADERS: Readonly<Record<string, string>> = {
  'X-Content-Type-Options': 'nosniff',
  // `frame-ancestors` above is the real control; this is for anything that
  // predates it. Both say the same thing.
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'no-referrer',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
  // Nothing here uses any of these, and a study app asking for them is a bug.
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()',
};

/** Every security header for one response. */
export function securityHeaders(isProduction: boolean): Record<string, string> {
  return isProduction
    ? { ...BASE_SECURITY_HEADERS, 'Content-Security-Policy': CONTENT_SECURITY_POLICY }
    : { ...BASE_SECURITY_HEADERS };
}

/**
 * The same headers again, as Cloudflare's `_headers` file, emitted into `dist/`
 * by the Vite build.
 *
 * The Worker cannot do this job. `run_worker_first` in `wrangler.jsonc` is
 * `["/api/*"]`, so the asset handler answers every other path *before* the
 * Worker is invoked — which means the code in `worker/index.ts` that wraps an
 * asset response never runs for a document request. Setting the CSP there and
 * nowhere else produced the exact inversion this file was written to avoid: the
 * policy on the JSON nobody renders, and nothing on the HTML that runs scripts.
 *
 * `run_worker_first: true` would fix it and would also turn every static asset
 * request into a billed Worker invocation, which is a poor trade for a header.
 * Cloudflare reads `_headers` in the asset directory instead, at no invocation
 * cost — and generating it here rather than checking a copy into `public/` is
 * what keeps one policy from becoming two that disagree.
 */
export function headersFileBody(): string {
  const all = { ...BASE_SECURITY_HEADERS, 'Content-Security-Policy': CONTENT_SECURITY_POLICY };
  const lines = ['# Generated by the Vite build from server/headers.ts. Do not edit.', '/*'];
  for (const [name, value] of Object.entries(all)) lines.push(`  ${name}: ${value}`);
  return `${lines.join('\n')}\n`;
}
